name: Crowdin Accessibility Issue
description: Report an accessibility issue with Crowdin's web interface
title: "[Accessibility]: "
labels: ["accessibility", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an accessibility issue with Crowdin! Please provide as much detail as possible to help us understand and address the problem.

  - type: textarea
    id: overview
    attributes:
      label: Overview of the issue
      description: Please provide a clear and concise description of the accessibility issue you encountered.
      placeholder: Describe the accessibility problem you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Use screen reader to...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Web browser
      description: Which web browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Internet Explorer
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description: What version of the browser are you using?
      placeholder: "e.g., 118.0.5993.88"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - Windows (other version)
        - macOS
        - Linux
        - iOS
        - Android
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: assistive-technology
    attributes:
      label: Screen reader or assistive technology
      description: Which assistive technology are you using?
      options:
        - NVDA
        - JAWS
        - VoiceOver (macOS)
        - VoiceOver (iOS)
        - TalkBack (Android)
        - Dragon NaturallySpeaking
        - Windows Narrator
        - Orca
        - Other (please specify in additional context)
        - None / Not applicable
    validations:
      required: true

  - type: input
    id: assistive-tech-version
    attributes:
      label: Assistive technology version
      description: What version of the assistive technology are you using? (if applicable)
      placeholder: "e.g., NVDA 2023.3"

  - type: dropdown
    id: impact
    attributes:
      label: Impact level
      description: How severely does this issue affect your ability to use Crowdin?
      options:
        - "High (I can't translate NVDA with this issue)"
        - "Medium (requires workaround, unintuitive/confusing experience)"
        - "Low (inefficient/bad experience)"
    validations:
      required: true

  - type: input
    id: crowdin-project
    attributes:
      label: Crowdin project/language
      description: Which Crowdin project and language were you working on when you encountered this issue?
      placeholder: "e.g., NVDA project, French translation"

  - type: textarea
    id: error-messages
    attributes:
      label: Error messages
      description: If you encountered any error messages, please include them here.
      placeholder: Copy and paste any error messages you saw...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. This might include:
        - Screenshots or screen recordings (if possible)
        - Console error messages from browser developer tools
        - Any workarounds you've discovered
        - Other details that might be relevant
      placeholder: Any additional information that might help us understand the issue...

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgments
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided sufficient detail for the development team to understand and reproduce the issue
          required: true